services:
  - type: web
    name: bingo-socket
    env: node
    buildCommand: npm install socket.io
    startCommand: node server-standalone.js
    envVars:
      - key: NODE_VERSION
        value: 20.9.0
