services:
  - type: web
    name: bingo-socket-server
    env: node
    buildCommand: npm install
    startCommand: node server-standalone.js
    envVars:
      - key: NODE_ENV
        value: production
